import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        marginTop: 50,
        flex: 1,
        backgroundColor: '#6cbff030',
        alignItems: 'stretch',
    },
    header: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 20,
        padding: 10,
    },
    modalWorkout: {
        flex: 0.4,
        justifyContent: 'space-evenly',
        alignItems: 'center',
        backgroundColor: '#b0cceb',
        margin: 30,
        borderRadius: 10,
        borderWidth: 1,
    },
    setButton: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: '#f2ffc2',
        borderRadius: 10,
        borderWidth: 1,
        padding: 10,
        marginLeft: 10,
        marginRight: 10,
        marginBottom: 10,
        alignItems: 'center',
    },
    setButtonText: {
        fontSize: 16,
        fontWeight: 'bold',
    },
    closeButton :{
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: '#fd8282',
        borderRadius: 10,
        borderWidth: 1,
        padding: 10,
        width: 200,
        alignItems: 'center',
    },
    modalButton: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: '#9bc7b8',
        borderRadius: 10,
        borderWidth: 1,
        padding: 10,
        width: 200,
        alignItems: 'center',
    },
    modalCalendar: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#b0cceb',
    },
    calendar: {
        borderRadius: 10,
        borderWidth: 1,
        padding: 10,
        marginBottom: 10,
    },
    total: {
        marginBottom: 10,
        backgroundColor: '#9bc7b8',
        marginLeft: 10,
        marginRight: 10,
        padding: 10,
        borderRadius: 10,
    },
    totalContainer: {
        flexDirection: 'row',
        padding: 10,
    },
    item: {
        flex: 1,
        marginBottom: 10,
        padding: 10,
        marginVertical: 8,
        marginHorizontal: 16,
        backgroundColor: '#f2ffc2',
    },
    itemHeader: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    itemHeaderText: {
        fontSize: 16,
        fontWeight: 'bold',
    },
    settingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f2ffc2',
        marginLeft: 10,
        marginRight: 10,
        paddingTop: 20,
        paddingBottom: 20,
        paddingLeft: 10,
        borderRadius: 10,
        marginBottom: 10,
    },
    settingMode: {
        fontSize: 16,
        fontWeight: 'bold',
        paddingLeft: 10
    },
    radio: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#9bc7b880',
        marginLeft: 10,
        marginRight: 10,
        padding: 5,
    },
    paperButton: {
        marginLeft: 5,
        marginRight: 5,
    },
    paperInput: {
        marginLeft: 10,
        marginRight: 10,
        marginBottom: 10,
    },
  });